apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cvyi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-cvyi@sha256:cabea844c0a725eb82f408697d08b349f90fbebab014e413e4d1d15766144b6e
        name: my-nodejs
        resources: {}
status: {}
